enum MessageDef {
	NONE = 0,
	/** TAG MSG */
	// TAG_CHANGE_PET_BATTLE,

	/** CFG MSG */
	CFG_UPDATE,
	CFG_UPDATE_MONS, // 怪物配置更新
	CFG_UPDATE_QIMEN,

	/** 子角色 */
	SUB_ROLE_CHANGE,
	SUB_ROLE_CREATE,

	// 外观
	DRESS_UPDATE,
	DRESS_FASHION_UPDATE,
	TITLE_UPDATE,

	// 血条更新
	ROLE_HP_CHANGE,

	/** 邮件 */
	MAIL_DATA_CHANGE,
	MAIL_GET_ITEM,
	OPEN_MAIL,

	/** 背包 */
	BAG_DEAL_SMELT,
	BAG_HUNT_STORE_CHANGE,
	BAG_ITEM_COUNT_CHANGE,
	BAG_WILL_FULL,
	BAG_WILL_RONG,
	BAG_WILL_USE,
	BAG_VOL_ADD,
	/** 背包道具更新 */
	BAG_EQUIP_JOB,
	BAG_EQUIP_JOB1,
	BAG_EQUIP_JOB2,
	BAG_EQUIP_JOB3,
	BAG_EQUIP_GOD,

	BAG_WX_EQUIP,//五行装备
	BAG_WX_EQUIP_JOB,
	BAG_WX_EQUIP_JOB1,
	BAG_WX_EQUIP_JOB2,
	BAG_WX_EQUIP_JOB3,

	BAG_JW_FLAG,//爵印装备更新

	BAG_EDGE_EQUIP,
	BAG_HOLY_EQUIP,
	BAG_SOUL_EQUIP,
	BAG_SOUL_EQUIP_RUNE,
	BAG_SOUL_EQUIP_RUNE_UPGRADE,
	BAG_TITLE, // 称号道具
	BAG_PICTORIAL, //图鉴
	BAG_QIMEN_EQUIP,
	BAG_TEJIE,//特戒
	BAG_PET_EQUIP,// 宠物装备

	PAGE_BUTTON_UPDATE,
	POWER_CHANGE,

	// 通用玩家信息
	CM_PLAYERINFO_INFO,

	// 活动数据
	ACTIVITY_UPDATE,
	ACTIVITY_INFO,
	ACTIVITY_DYNAMIC_ICON,
	ACTIVITY_WIN_RED,	// 活动界面标签栏红点刷新
	ACTIVITY_QIPAO_ICON,

	ACTIVITY_22_CRIT, // 22类型暴击

	// 角色数据
	INIT_ACTOR,
	NAME_CHANGE,
	LEVEL_CHANGE,
	DIAMOND_CHANGE,
	YB_CHANGE,
	GOLD_CHANGE,
	EXP_CHANGE,
	POWER_BOOST,
	CHANGE_EQUIP,
	LUCK_CHANGE,

	CHANGE_EQUIP_ZS,
	CHANGE_EQUIP_FS,
	CHANGE_EQUIP_DS,
	// 装备外观更新
	EQUIP_APPE_UPDATE,

	ROLE_HINT,

	ITEM_COMPLEX_SUCCESS,
	ITEM_COUNT_CHANGE,

	postUseItemSuccess,

	ITEM_EQUIP_COUNT_CHANGE,
	ITEM_OTHER_COUNT_CHANGE,
	ITEM_QIMEN_COUNT_CHANGE,
	RAID_KILL_MONSTER_COUNT,
	CHAPTERMAP_CHANGE,

	RAID_CHANGE,
	GUANQIA_CHANGE,
	GUANQIA_ROBOT,	// 关卡机器人
	GUANQIA_ROBOT_CREATE,	// 关卡机器人

	FORGE_ITEM_01_UPDATE,
	FORGE_ITEM_02_UPDATE,
	FORGE_ITEM_03_UPDATE,
	FORGE_ITEM_04_UPDATE,
	// FORGE_UPDATE,
	BOOST_UPDATE,
	REFINE_UPDATE,
	EXERCISE_UPDATE,
	GEM_UPDATE,
	FORGE_AUTO_UPDATE,
	// RP_FORGE,
	// FULI_GET_GIFT_SUCCEED,
	// FULI_MONTH_WEEK_CHANGE,
	// FULI_GET_HAVEBRIBERY,
	// FULI_GIVEGOLD_INFO,
	// FULI_GOLDTREE_INFO,
	// FULI_GET_REDEEMCODE,
	// FULI_GET_RECEIVEITEMSIGN,
	// FULI_GET_RECEIVEBRIBERY,
	// FULI_MONTH_SIGN_IN_CHANGE,
	PLAYER_CHANGE_SYSTEM_SETTING,
	GAME_SERVER_UPDATE_DAY,
	//VIP_LEVEL_CHANGE,
	//UPDATA_VIP_EXP,
	//UPDATA_VIP_AWARDS,
	VIP_DATA_CHANGE,
	// VIP_BUY_GIFT_CHANGE,
	// BATTLE_CHANGE,
	GUILD_CONTRIB_UPDATE,
	GUILD_INTEGRAL_NUMER_CHANGE,
	ROLE_TRANSITION,
	MULBUTTON_CHOOSE,
	TOGGLE_CHOOSE,

	// 神器
	ARTIFACT_UPDATE,
	ARTIFACT_ACT,

	// 材料副本
	MATERIAL_UPDATE,

	// 副本数据更新
	// RAID_ENTITY_UPDATE_COUNT,	// 玩家数量更新
	RAID_PLAYER_UPDATE_COUNT,	// 玩家数量更新

	// 神秘商店
	SHOP_REFRESH,
	SHOP_REFRESH_ITEM,//单个刷新
	SHOP_RED_POINT,

	// 技能
	SKILL_UPGRADE,

	//装备合成
	EQUIP_COMPOSITE_INDEX_CLICK,
	EQUIP_COMPOSITE_INDEX_LABEL_CLICK,
	EQUIP_COMPOSITE_QUALITY_CLICK,
	EQUIP_CMOPOSITE_MATERIAL_CLICK,
	EQUIP_COMPOSITE_RESULT,

	//图鉴
	PICTORIAL_RESOLVE_UPDATE,
	PICTORIAL_DATA_UPDATE,
	PICTORIAL_RESOLVE,

	// 个人boss
	PERSONAL_BOSS_UPDATE,

	// 野外boss
	FIELD_BOSS_UPDATE_DATA,
	FIELD_BOSS_UPDATE_LIST,
	FIELD_BOSS_BELONG,
	FIELD_BOSS_REMAIN,

	// 奇门boss
	QIMEN_BOSS_UPDATE_DATA,
	QIMEN_BOSS_UPDATE_LIST,
	QIMEN_BOSS_BELONG,
	QIMEN_BOSS_REMAIN,

	// 爵位boss
	BANNERET_BOSS_UPDATE_DATA,
	BANNERET_BOSS_UPDATE_LIST,
	BANNERET_BOSS_BELONG,
	BANN_BOSS_REMAIN,

	// 积分boss
	INTEGRAL_BOSS_UPDATE,

	//沙城争霸
	SHABAK_INFO_BASE,
	SHABAK_INFO,
	SHABAK_RANK,//排名积分
	SHABAK_DAMAGE,
	SHABAK_SCENE,//场景切换
	SHABAK_WAR,//战场开始
	SHABAK_FLAG_ONWER,//旗子归属
	SHABAK_ONWER,//沙城归属
	SHABAK_SCORE,//积分
	SHABAK_FIGHTING_INFO,//战况信息
	SHABAK_FIGHT_STATE,//争霸阶段改变
	SHABAK_GOTO_ATK,//寻路攻击中立单位
	SHABAK_ATK,//直接攻击单位
	// SHABAK_ATK_E,//攻击其他工会单位
	SHABAK_FLAG_MOVE,//寻路去夺旗-复活点争夺
	SHABAK_BOSS_STATUS,//沙巴克雕像状态

	//帝兵装备
	EDGE_EQUIP_WEAR,
	EDGE_EQUIP_COMPOSE,
	EDGE_MATERIAL_SELECTED,
	EDGE_ITEM_COMPOSE,

	// 宠物
	PET_LV_CHANGE,
	PET_ZY_CHANGE,
	PET_SKIN_CHANGE,
	PET_SKIN_SWITCH_CHANGE,
	PET_UPDATE_INFO,
	PET_EQUIP_StRONG_SUCCESS,
	PETGIFT_UPDATE,
	PET_POWER_CHANGE,
	PET_CHANGE_FREE_PARSLYSIS,
	PET_FRIST_ADD_PARSLYSIS,


	//四圣装备
	SSZB_EQUIP_SELECT_ITEM,
	SSZB_EQUIP_SUCC_ITEM,
	SSZB_EQUIP_POWER_UPDATE,
	SSZB_EQUIP_TAG_UPDATE,


	// 圣装
	HOLY_ITEM_INDEX,
	HOLY_COMPLEX_CHANGE,
	HOLY_ROLE_CHANGE,
	HOLY_SMELT,
	HOLY_TITLE_INDEX,

	//五行
	WX_EQUIP_UPDATE_ROLE,
	WX_EQUIP_XL_SELECTS,
	WX_EQUIP_UP,//穿戴五行装备
	WX_XL_Z_H_SUCC,//注魂成功
	WX_MERGE_SUCC, //五行合成成功
	WX_MERGE_ITEM_UPDATE, //材料变更

	//魂装
	SOUL_EQUIP_INFO_UPDATE,
	SOUL_EQUIP_STAGE_CLICK,
	SOUL_EQUIP_LEVEL_CLICK,
	SOUL_EQUIP_RUNE_CHOOSE,
	SOUL_EQUIP_COMPOSE_RESULT,
	SOUL_EQUIP_RESOLVE_CHANGE,
	SOUL_EQUIP_ACTIVE_SKILL,

	// 任务
	UPDATE_TASK,

	PLOT_PLAY_END,

	//爵位
	JW_EXP,//爵位荣誉积分变动
	/** 爵位信息更新 */
	JW_INFO_UPDATE,
	JW_UPDATE_TASK,//爵位任务更新
	JW_UPDATE_FLAG,//印记领取更新
	JW_FLAG_UP,//爵位印记更新
	JW_CHAPTER,//爵位章节奖励
	JW_UP_LV,//爵位升级
	JW_FLAG_EQUIP_UP,//爵位装备更新

	//遗迹boss
	YJ_BOSS_NUM_REF,//次数刷新
	YJ_BOSS_BELONG,//归属通知
	YJ_BOSS_ITEM_REF,//单个boss刷新
	// YJ_BOSS_ITEM_REF_FH,//单个boss复活
	YJ_BOSS_REF_HF,//单人回血CD
	/** boss复活TIP param:{id:怪物展示ID, name?: 名字(为空读表), level?:等级(为空读表), head?:头像(为空读表), link?: new () => BaseView | ViewId (跳转目标链接 跳转ID或者类名), param?:透传参数} */
	BOSS_REVIVE,//BOSS复活TIP {id:怪物展示ID, name?: 名字(为空读表), level?:等级(为空读表), head?:头像(为空读表), link?: new () => BaseView | ViewId (跳转目标链接 跳转ID或者类名), param?:透传参数} */

	//奇门装备
	QIMEN_EQUIP_CHOOSE,
	QIMEN_EQUIP_RESOLVE_CHANGE,
	QIMEN_EQUIP_INFO_UPDATE,

	//排行榜
	RANK,//爵位 data:RankConst
	RANK_JW,//爵位
	RANK_WORSHIP,//膜拜信息

	//经脉
	ACUPOINT_UPDATE,
	ACUPOINT_UPDATE_UI,
	ACUPOINT_ITEM_UPDATE,

	// GM
	GM_GUAN_JUMP,

	// 经验副本
	FBEXP_UPDATE,

	// BOSS之家
	BOSSHOME_CHOOSE,
	BOSSHOME_UPDATE_DATA,
	BOSSHOME_UPDATE_INFO,
	BOSSHOME_RELIVE,
	BOSSHOME_UPDATE_BELONG,

	//世界BOSS
	WORLD_BOSS_UPDATE,
	WORLD_BOSS_HURTLIST,
	/** 副本-幻境 */
	DREAMLAND_FB_UPDATE,

	// 行会
	GUILD_LEAVE,
	GUILD_BUILD_CHANGE,
	GUILD_APPLY_CHANGE,
	GUILD_MEMBERLIST_CHANGE,
	GUILD_DONATE_CHANGE,
	GUILD_SKILL_CHANGE,
	GUILD_LIST_CHANGE,
	GUILD_LIST_APPLY_CHANGE,
	GUILD_CHANGE_NOTICE,
	GUILD_MESSAGE_CHANGE,
	GUILD_INFO_CHANGE,
	GUILD_ID_CHANGE,

	//行会Boss
	GUILD_BOSS_UPDATE,
	GUILD_BOSS_COUNT,
	GUILD_BOSS_REWARD,
	GUILD_BOSS_RANK_UPDATE,

	//特戒
	TEJIE_UPDATE,
	TEJIE_COMPOSE,
	/** 镇魔塔 */
	MONSTER_TOWER_UPDATE,
	//BOSS首杀
	FIRST_KILL_BOSS_MESSAGE,

	//拍卖行
	AUCTION_LIST,
	AUCTION_LIST_UPDATE,
	AUCTION_NOTICE,
	AUCTION_RECORD,
	AUCTION_STATE,

	//聊天
	CHAT_NEW_MESSAGE,

	//功能预告
	FUNC_OPEN_CHANGE,
	//法宝
	TREASURE_ACT_CHANGE,
	TREASURE_SKILL_CHANGE,

	// 狂暴之力
	RAGE_CHANGE,

	//未知暗殿
	UNKNOWN_AUTO_SUCCESS,
	UNKNOWN_LIST,
	UNKNOWN_UPDATE,
	UNKNOWN_CLICK,
	UNKNOWN_AUTO_SELECTED,
	UNKNOWN_MONEY,

	//红包
	RED_ENVELOPE_UPDATE,
	RED_ENVELOPE_SEND_RSP,

	// 沙城捐献
	SCJX_DATA_CHANGE,

	// 可穿戴新装备
	HAS_NEW_EQUIP,
	HAS_NEW_SOUL_EQUIP,
	HAS_NEW_QIMEN_EQUIP,
	HAS_NEW_TEJIE_EQUIP,
	HAS_NEW_HOLY_EQUIP,
	HAS_NEW_MATERIAL,
	HAS_PET_EQUIP,// 宠物装备更新

	//竞技场
	ARENA_INFO,
	ARENA_BOX_INFO,//宝箱领取状态
	ARENA_TIMES,//次数刷新
	ARENA_CHALLENGE_RECORD,//挑战记录
	ARENA_RANK_LIST,//挑战列表

	//玛法寻宝
	MARFA_TREASURE_UPDATE_RECORDS, //普通|限时寻宝记录更新
	MARFA_HIMITSU_TREASURE_UPDATE,//秘宝具体数据更新
	MARFA_DEPOT_UPDATE, //仓库数据更新
	// MARFA_ALL_INFO, //三个玛法活动数据更新
	MARFA_DRAWPROP_NUM_CHANGE, //宝库寻宝道具数量
	MARFA_HIMITSU_RESULT, //秘宝抽奖更新

	// 押镖
	DART_UPDATE,	// 押镖信息更新
	DART_QUALITY_CHANGE,	// 镖车品质刷新
	DART_NUM_CHANGE,		// 押镖次数更新
	ROB_RECORD_CHANGE,		// 劫镖记录更新

	//每日签到
	DAILY_SIGN_UPDATE,

	//日常任务
	DAILY_TASKS,
	DAILY_TASK_ITEM,
	DAILY_TASK_LV,
	DAILY_TASK_LV_REWARD,

	// 登录奖励
	LOGIN_REWARD_CHANGE,	// 登录奖励更新

	//好友
	FRIEND_INITED,
	FRIEND_UPDATE_INFO,
	FRIEND_PLAYER_INFO,
	FRIEND_PRIVATE_CLICK,
	FRIEND_PRIVATE_MESSAGE,

	// 资源找回
	RETRIEVE_DATA_CHANGE,
	//首充
	FIRST_RECHARGE,
	PRIVILEGE_CHANGE, //特权卡
	RECHARGE_CHANGE,
	RECHARGE_SUCCEED, //充值成功

	//主界面当前活动更新消息
	MAIN_ACTIVITY,

	// 怪物攻城
	MONSTER_BOSS_CHANGE,
	MONSTER_BOSS_PROGRESS_CHANGE,
	MONSTER_ATK,

	//封魔大乱斗
	SCRIMMAGE_FLAG,
	SCRIMMAGE_FLAG_ASCRIP,
	SCRIMMAGE_RANK,

	//元宝回收
	RESAVE_SMELT,
	//金猪来袭
	GOLDEN_PIG_UPDATE,

	// 变强
	TO_STRONG_TASK_CHANGE,
	TO_STRONG_SCORE_REWARD_CHANGE,

	// 神装分解
	GOD_EQUIP_RESOLVE_CHANGE,

	// 大富翁
	BIG_RICH_UPDATE,
	BIG_RICH_RANDOM_SUCCESS,

	// 砍一刀详情界面更新
	CHOP_DETAIL_TIPS_UPDATE,

	// 翻牌探宝
	CARD_TURNOVER_RST,
	// CARD_TURNOVER_PROP_UPDATE,
	CARD_TURNOVER_BIGAWARD_GET,

	// 白日门
	BRM_PREINFO,
	BRM_UPDATE_RANK,
	BRM_UPDATE_COLL,
	BRM_TRANS,
	BRM_UPDATE_PHASE,

	// 魂器
	SOUL_EQUIP_SMELT_CHOOSED,
	SOUL_EQUIP_SMELT_ITEM_CHOOSED,
	SOUL_EQUIP_SMELT_SUCCESS,
	HORCRUX_TALENT_UPDATE,
	//天下第一
	JOB_ARENA_BATTLE,
	JOB_ARENA_SIGN,

	//切割武魂
	QGWH_INFO,
	QGWH_UP_LEVEL,

	//魔魂
	DEMON_SOUL_INFO,
	DEMON_SOUL_UP_LEVEL,

	// 在上面定义
	MAX,
}
namespace MessageDefFunc {
	export let MAX = MessageDef.MAX

	// -1000
	export function CUSTOM_DRESS(roleId: number, type: number) {
		return -1000 - MessageDef.MAX + roleId * 100 + type
	}
	// -2000
	export function CUSTOM_DRESS_ZIZHI_ITEM(type: number) {
		return -2000 - MessageDef.MAX + type
	}
	// -3000
	export function CUSTOM_DRESS_LV_ITEM(type: number) {
		return -3000 - MessageDef.MAX + type
	}

	// -4000 //爵位自定义事件
	export function CUSTOM_DRESS_JW_ITEM(type: number) {
		return -4000 - MessageDef.MAX + type
	}
	// -5000 //日常自定义事件
	export function CUSTOM_DRESS_DAILY_ITEM(type: number) {
		return -5000 - MessageDef.MAX + type
	}

	// -6000 
	// export function CUSTOM_ACT_OPEN_ID(openId: number) {
	// 	return -6000 - openId
	// }

	// -7000 
	export function CUSTOM_ACT_MAIN_ID(mainId: number) {
		return -7000 - mainId
	}

	// -1000000000
	export function CUSTOM_ITEM_ID(itemId: number) {
		return -2100000000 - MessageDef.MAX + itemId
	}
}

// {
// 	if (DEBUG) {
// 		let max = MessageDef.MAX
// 		let keys = Object.keys(MessageDef)
// 		for (let val of keys) {
// 			if (typeof (val) == "number") {
// 				if (val > max) {
// 					throw "消息定义错误"
// 				}
// 			}
// 		}
// 	}
// }